import { Router } from "express";
import authRoutes from "../modules/auth/auth.routes";
import usersRoutes from "../modules/users/users.routes";
import profileRoutes from "../modules/profile/profile.routes";
import goalsRoutes from "../modules/goals/goals.routes";
import foodsRoutes from "../modules/foods/foods.routes";
import mealsRoutes from "../modules/meals/meals.routes";
import exercisesRoutes from "../modules/exercises/exercises.routes";
import workoutsRoutes from "../modules/workouts/workouts.routes";
import cardioRoutes from "../modules/cardio/cardio.routes";
import wearablesRoutes from "../modules/wearables/wearables.routes";
import progressRoutes from "../modules/progress/progress.routes";
import reportsRoutes from "../modules/reports/reports.routes";
import adminRoutes from "../modules/admin/admin.routes";
import leaderboardRoutes from "../modules/leaderboard/leaderboard.routes";
import socialRoutes from "../modules/social/social.routes";
import postsRoutes from "../modules/posts/posts.routes";
import feedRoutes from "../modules/feed/feed.routes";
import messagesRoutes from "../modules/messages/messages.routes";
import notificationsRoutes from "../modules/notifications/notifications.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/profile", profileRoutes);
router.use("/goals", goalsRoutes);
router.use("/foods", foodsRoutes);
router.use("/meals", mealsRoutes);
router.use("/exercises", exercisesRoutes);
router.use("/workouts", workoutsRoutes);
router.use("/cardio", cardioRoutes);
router.use("/wearables", wearablesRoutes);
router.use("/progress", progressRoutes);
router.use("/reports", reportsRoutes);
router.use("/admin", adminRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/social", socialRoutes);
router.use("/posts", postsRoutes);
router.use("/feed", feedRoutes);
router.use("/messages", messagesRoutes);
router.use("/notifications", notificationsRoutes);

export default router;
